<?php


class Aluno extends Pessoa
{
    private $matricula, $curso;
    public function pagarMensalidade()
    {
        echo "Pagando mensalidade do aluno $this->getNome()";
    }

    /**
     * @return mixed
     */
    public function getMatricula()
    {
        return $this->matricula;
    }

    /**
     * @return mixed
     */
    public function getCurso()
    {
        return $this->curso;
    }

    /**
     * @param mixed $matricula
     */
    public function setMatricula($matricula): void
    {
        $this->matricula = $matricula;
    }

    /**
     * @param mixed $curso
     */
    public function setCurso($curso): void
    {
        $this->curso = $curso;
    }


}

class Bolsista extends Aluno
{
    private $bolsa;

    public function renovarBols()
    {

    }

    public function pagarMensalidade()
    {
        parent::pagarMensalidade(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getBolsa()
    {
        return $this->bolsa;
    }

    /**
     * @param mixed $bolsa
     */
    public function setBolsa($bolsa): void
    {
        $this->bolsa = $bolsa;
    }
}